### ISSUE TITLE
Do you run cli from src?  error no typer

### ISSUE THREAD

**Issue by stoneyv** [EthanRosenthal/medium-data-bakeoff#9]
This is my first experience with poetry and typer.

I invoked the cli medium_data_bakeoff --help command from the src directory.  It complains about typer, but I see typer installed during poetry install as well as the docker image build.  When I run a repl and try to import typer, it does not exist.

```
stoney@laptop2:~/Desktop/medium-data-bakeoff/src$ python -m medium_data_bakeoff --help
Traceback (most recent call last):
  File "/home/stoney/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stoney/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stoney/Desktop/medium-data-bakeoff/src/medium_data_bakeoff/__main__.py", line 1, in <module>
    from medium_data_bakeoff.cli import app
  File "/home/stoney/Desktop/medium-data-bakeoff/src/medium_data_bakeoff/cli.py", line 1, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
stoney@laptop2:~/Desktop/medium-data-bakeoff/src$ python
Python 3.9.5 (default, Jun  7 2021, 16:57:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'typer'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()

```

**Comment by EthanRosenthal** [comment]
Hmm I should add some more `poetry`-specific explanation. I don't usually use `poetry` to manage my virtual environments; I only use it for installing dependencies.

Regardless, you shouldn't need to `cd` into `src` in order to run the code. Once you've run `poetry install`, you should be able to call the package from any directory. 

I have occasionally had some weird issues with some combination of `pyenv` + `poetry` that I don't quite understand where, after installing with poetry, I then have to open a new shell and activate my environment in order to get things to fully work. Let me know if that works for you!
